# Generated by Django 3.1.3 on 2020-11-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('position', models.CharField(default=0, max_length=5)),
                ('group_size', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='123@gmail.com', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_business', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='123@gmail.com', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('store_name', models.CharField(default='', max_length=100)),
                ('store_number', models.CharField(default='', max_length=12)),
                ('store_address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='New York', max_length=30)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipcode', models.CharField(default='', max_length=5)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=True)),
                ('sunday_open', models.CharField(default='00:00', max_length=5)),
                ('sunday_closed', models.CharField(default='00:00', max_length=5)),
                ('monday_open', models.CharField(default='00:00', max_length=5)),
                ('monday_closed', models.CharField(default='00:00', max_length=5)),
                ('tuesday_open', models.CharField(default='00:00', max_length=5)),
                ('tuesday_closed', models.CharField(default='00:00', max_length=5)),
                ('wednesday_open', models.CharField(default='00:00', max_length=5)),
                ('wednesday_closed', models.CharField(default='00:00', max_length=5)),
                ('thursday_open', models.CharField(default='00:00', max_length=5)),
                ('thursday_closed', models.CharField(default='00:00', max_length=5)),
                ('friday_open', models.CharField(default='00:00', max_length=5)),
                ('friday_closed', models.CharField(default='00:00', max_length=5)),
                ('saturday_open', models.CharField(default='00:00', max_length=5)),
                ('saturday_closed', models.CharField(default='00:00', max_length=5)),
                ('store_capacity', models.IntegerField(default=10)),
                ('group_limit', models.IntegerField(default=1)),
                ('in_line', models.IntegerField(default=0)),
                ('in_store', models.IntegerField(default=0)),
                ('scheduled', models.IntegerField(default=0)),
                ('all_tickets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.all_customers')),
            ],
        ),
    ]
