# Generated by Django 3.1.2 on 2020-10-18 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_business_business1_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='business',
            name='cellnumber',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='business',
            name='business',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(default='New York', max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='input_sex',
            field=models.CharField(default='Mr.', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='business',
            name='store_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='store_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='store_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='business',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Business1',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
