# Generated by Django 3.1.1 on 2020-10-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201007_0143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
