# Generated by Django 3.1.2 on 2020-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201018_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='input_sex',
            field=models.CharField(default='', max_length=3),
        ),
    ]
