# Generated by Django 3.1.3 on 2020-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_business_store_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='store_capacity',
            field=models.IntegerField(default=100),
        ),
    ]
