# Generated by Django 3.1.2 on 2020-10-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201018_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
