# Generated by Django 3.1.2 on 2020-10-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerProfile',
        ),
    ]
