# Generated by Django 3.1.2 on 2020-10-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201018_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer1',
        ),
    ]
