# Generated by Django 3.1.2 on 2020-10-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_customer3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='zipcode',
        ),
    ]
