# Generated by Django 3.1.2 on 2020-10-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201018_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer',
        ),
    ]
