# Generated by Django 3.1.2 on 2020-10-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
