# Generated by Django 3.1.2 on 2020-10-18 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0021_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cell_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='kay@aol.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='KAy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Hay', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default='123', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='123@gmail.com', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('password1', models.CharField(default='', max_length=30)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_business', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
