# Generated by Django 3.1.2 on 2020-10-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20201018_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(default='123@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
