# Generated by Django 3.1.2 on 2020-10-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_business_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='username',
        ),
    ]
