# Generated by Django 3.1.2 on 2020-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20201023_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
