# Generated by Django 3.1.2 on 2020-10-23 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0028_auto_20201023_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business',
            new_name='Business1',
        ),
    ]
