# Generated by Django 3.1.2 on 2020-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20201023_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='123@gmail.com', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('store_name', models.CharField(default='', max_length=100)),
                ('store_number', models.CharField(default='', max_length=12)),
                ('store_address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='New York', max_length=30)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipcode', models.CharField(default='', max_length=5)),
                ('input_sex', models.CharField(default='', max_length=3)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=True)),
            ],
            bases=(models.Model,),
        ),
        migrations.DeleteModel(
            name='Business1',
        ),
    ]
