# Generated by Django 3.1.2 on 2020-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20201023_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
