# Generated by Django 3.1.2 on 2020-10-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_business_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='friday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='friday_open',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='monday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='monday_open',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='satuday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='saturday_open',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='sunday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='sunday_open',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='thursday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='thursday_open',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='tuesday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='tuesday_open',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='wednesday_closed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='wednesday_open',
            field=models.CharField(default='', max_length=5),
        ),
    ]
