# Generated by Django 3.1.2 on 2020-10-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20201026_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='satuday_closed',
            new_name='saturday_closed',
        ),
    ]
