# Generated by Django 3.1.2 on 2020-10-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20201026_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='input_sex',
        ),
    ]
